<?php

/**
 * @file
 * Contains feedback_form.module
 */

use Drupal\node\Entity\Node;

function createSubmissionForm($form_state) {
    $node = Node::create([
        'type'  => 'submitted_feedback_form',
        'title' => 'Submitted Feedback Forms',
        'path'  => '/submitted-feedback-forms',
    ]);

    $node->set('field_feedback_title', $form_state->getValue('feedback_title'));
    $node->set('field_full_sender_name', $form_state->getValue('name'));
    $node->set('field_feedback_description', $form_state->getValue('feedback_description'));
    
    
    $node->setPublished();
    $node->save();

    // $node->set('title', 'Feedback Form');

    
}